### ISSUE TITLE
Support for 5.24

### ISSUE THREAD

**Issue by Medullitus** [luisbocanegra/kwin-window-activity-switcher#2]
Hello. Thank you for the addon. Could you please provide support for the KDE Plasma 5.24 version?

**Comment by luisbocanegra** [comment]
Hi, I run Plasma 6 these days and have very little interest in porting this to Plasma 5.x

Is there a particular reason you haven't updated to a newer version or plasma, not even to the last stable 5.x version?

**Comment by Medullitus** [comment]
Hello,

Thank you very much for your response and attention.

Unfortunately, KDE Plasma 6 does not provide enough stability and is still a version that hasn't fully settled. For example, it is not possible for me to use Latte, which I use actively and am very satisfied with, in Plasma 6. I also have doubts about the stability of the Kio Gdrive plugin for Dolphin. That's why I continue with Kubuntu 22.05, which I believe is more stable.

However, I am experiencing a significant issue with KDE activities. I have three activities: A, B, and C. My main activity is A. I want to use the Z application in both A and B activities. But every time I restart my computer, I have to manually move the Z application from my A activity to my B activity. If this could happen automatically, it would make things easier. I would like to use your addon because I believe it could help with this. Thank you...

**Comment by luisbocanegra** [comment]
Understandable, I too was a Latte user, but now I am mostly happy with Plasma Panels + my other project [Panel Colorizer](https://github.com/luisbocanegra/plasma-panel-colorizer), can't say about Gdrive stability in the last 5.x or 6.x as I don't use it.

> However, I am experiencing a significant issue with KDE activities. I have three activities: A, B, and C. My main activity is A. I want to use the Z application in both A and B activities. But every time I restart my computer, I have to manually move the Z application from my A activity to my B activity. If this could happen automatically, it would make things easier. I would like to use your addon because I believe it could help with this.

Currently this project allows moving one or all windows between activities or to all of them, but doesn't have the option to show a window in a specific activity which was previously requested in https://github.com/luisbocanegra/kwin-window-activity-switcher/issues/1 but haven't looked into that yet.

But if your use case isn't switching windows regularly and just want to have some window show in multiple activities all the time that is possible with a window rule, at least on Plasma 6:

![Screenshot_20241023_012506](https://github.com/user-attachments/assets/1f7e7e07-839e-4cb3-aa76-86d0e560ce35)

**Comment by Medullitus** [comment]
> Understandable, I too was a Latte user, but now I am mostly happy with Plasma Panels + my other project [Panel Colorizer](https://github.com/luisbocanegra/plasma-panel-colorizer), can't say about Gdrive stability in the last 5.x or 6.x as I don't use it.
> 
> > However, I am experiencing a significant issue with KDE activities. I have three activities: A, B, and C. My main activity is A. I want to use the Z application in both A and B activities. But every time I restart my computer, I have to manually move the Z application from my A activity to my B activity. If this could happen automatically, it would make things easier. I would like to use your addon because I believe it could help with this.
> 
> Currently this project allows moving one or all windows between activities or to all of them, but doesn't have the option to show a window in a specific activity which was previously requested in #1 but haven't looked into that yet.
> 
> But if your use case isn't switching windows regularly and just want to have some window show in multiple activities all the time that is possible with a window rule, at least on Plasma 6:
> 
> ![Screenshot_20241023_012506](https://private-user-images.githubusercontent.com/15076387/379148286-1f7e7e07-839e-4cb3-aa76-86d0e560ce35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDQ3MjksIm5iZiI6MTcyOTcwNDQyOSwicGF0aCI6Ii8xNTA3NjM4Ny8zNzkxNDgyODYtMWY3ZTdlMDctODM5ZS00Y2IzLWFhNzYtODZkMGU1NjBjZTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE3MjcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YTk2NDQ3Y2Q2ZWZmZmI1NTY2MDE3ZTIxMWU5NjA5YjA0YjNjMmI5YjBmZWE1ZDFjN2NmOGNiY2MwNjNkNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ijo0WMslbhZx9SqJPSH2lYjEGO85pds9rXWjhCcTqV0)

Wow, it works! Thank you so much for your suggestion! You're awesome!

By the way, it would be great if dedicated and talented developers like you contributed to Latte. Please keep that in mind.

Long live Free Software! Long live Linux!!!
